/* OSRS Journey QoL suite: additive overrides only; no existing profile data is rewritten. */
Object.assign(ui, {
  achievementLimits: { diaries: 8, combat: 48, collection: 60 },
  goalDraftMode: '', goalDraftType: '', goalDrawerIdentity: '', pendingSkill: ''
});

function qolGoalCatalog(kind) {
  if (kind === 'bossId') return state.bosses.catalog.map(item => ({ value: item.id, label: item.name }));
  if (kind === 'diaryTarget') return progressionCatalogs.diaries.flatMap(group => group.tasks.map(task => ({ value: `${group.region}|${group.tier}|${task.index}`, label: `${group.region} · ${group.tier} · ${task.name}` })));
  if (kind === 'caId') return progressionCatalogs.combatAchievements.filter(item => !combatCompletedSet().has(item.id)).map(item => ({ value: String(item.id), label: `${item.monster} · ${item.name}` }));
  if (kind === 'collectionItemId') return progressionCatalogs.collectionLog.filter(item => !collectionCompletedSet().has(item.item_id)).map(item => ({ value: String(item.item_id), label: item.item_name }));
  if (kind === 'collectionSource') return [...new Set(progressionCatalogs.collectionLog.flatMap(item => item.sources || []))].sort().map(value => ({ value, label: value }));
  if (kind === 'slayerMonster' && typeof slayerCatalog !== 'undefined') return slayerCatalog.map(item => ({ value: item.id, label: item.name }));
  return [];
}

function qolPicker(name, label, selectedValue, selectedLabel, hint='Digite para pesquisar…') {
  const rows=qolGoalCatalog(name), selected=rows.find(row=>String(row.value)===String(selectedValue));
  const currentLabel=selectedLabel||selected?.label||'';
  return `<label class="catalog-picker">${label}<input type="search" data-catalog-search="${name}" value="${esc(currentLabel)}" placeholder="${esc(hint)}" autocomplete="off"><input type="hidden" name="${name}" value="${esc(selectedValue||'')}"><small class="catalog-selected">${currentLabel?`Selecionado: ${esc(currentLabel)}`:`${rows.length} opções disponíveis`}</small><div class="catalog-picker-results" data-catalog-results="${name}">${qolPickerRows(name,'')}</div></label>`;
}

function qolPickerRows(kind, query='') {
  const needle=String(query).trim().toLowerCase(),rows=qolGoalCatalog(kind).filter(row=>!needle||row.label.toLowerCase().includes(needle)).slice(0,40);
  return rows.length?rows.map(row=>`<button type="button" data-catalog-option="${kind}" data-value="${esc(row.value)}" data-label="${esc(row.label)}">${esc(row.label)}</button>`).join(''):`<span class="catalog-empty">Nenhum resultado.</span>`;
}

function qolModeFields(goal, mode, linkedQuest='') {
  if (mode==='quest') { const available=[...state.quests.items].filter(item=>Number(item.state)!==2||item.name===(goal?.questName||linkedQuest)).sort((a,b)=>Number(b.state)-Number(a.state)||a.name.localeCompare(b.name)); return `<label>Quest vinculada<select name="questName"><option value="">Selecione uma quest pendente</option>${available.map(item=>`<option value="${esc(item.name)}" ${(goal?.questName||linkedQuest)===item.name?'selected':''}>${esc(item.name)} · ${questStateLabel(item.state)}</option>`).join('')}</select><small>Somente quests não concluídas deste personagem.</small></label>`; }
  if (mode==='skill') return `<div class="form-two"><label>Skill<select name="skill"><option value="">Selecione</option>${state.skills.map(item=>`<option ${goal?.skill===item.name?'selected':''}>${item.name}</option>`).join('')}</select></label>${qolTarget(goal)}</div>`;
  if (mode==='boss') return `${qolPicker('bossId','Boss',goal?.bossId,'','Busque o boss…')}${qolTarget(goal)}`;
  if (mode==='raid') return `<div class="form-two"><label>Raid<select name="raidId"><option value="">Selecione</option>${Object.values(state.raids.items).map(item=>`<option value="${item.id}" ${goal?.raidId===item.id?'selected':''}>${esc(item.name)}</option>`).join('')}</select></label>${qolTarget(goal)}</div>`;
  if (mode==='diaryTask') return qolPicker('diaryTarget','Tarefa de Achievement Diary',goal?.diaryRegion?`${goal.diaryRegion}|${goal.diaryTier}|${goal.diaryTaskIndex}`:'','','Busque região, tier ou tarefa…');
  if (mode==='diaryTier') { const regions=[...new Set(progressionCatalogs.diaries.map(item=>item.region))].sort(); return `<div class="form-two"><label>Região<select name="diaryRegion"><option value="">Selecione</option>${regions.map(value=>`<option ${goal?.diaryRegion===value?'selected':''}>${esc(value)}</option>`).join('')}</select></label><label>Tier<select name="diaryTier"><option value="">Selecione</option>${tierOrder.map(value=>`<option ${goal?.diaryTier===value?'selected':''}>${value}</option>`).join('')}</select></label></div>`; }
  if (mode==='combatAchievement') return qolPicker('caId','Combat Achievement',goal?.caId,'','Busque boss, tarefa ou mecânica…');
  if (mode==='collectionItem') return qolPicker('collectionItemId','Item do Collection Log',goal?.collectionItemId,'','Busque o item…');
  if (mode==='collectionSource') return qolPicker('collectionSource','Página do Collection Log',goal?.collectionSource,'','Busque a página ou atividade…');
  if (mode==='composite') return `<label>Metas que compõem o objetivo<select name="components" multiple size="6">${state.goals.filter(item=>item.id!==goal?.id&&item.status!=='archived').map(item=>`<option value="${item.id}" ${(goal?.components||[]).includes(item.id)?'selected':''}>${esc(item.title)}</option>`).join('')}</select><small>Ctrl + clique seleciona mais de uma meta.</small></label>`;
  if (mode==='gearLoadout') return `<div class="merged-tool-note"><strong>Gear Lab conectado</strong><p>O progresso usa os itens exigidos que já estavam salvos nesta meta. Edite o loadout no Gear Lab para trocar os equipamentos.</p></div>`;
  if (mode==='slayerTask'||mode==='slayerKills') return `${qolPicker('slayerMonster','Monstro / task de Slayer',goal?.slayerMonster,'','Busque o monstro…')}${qolTarget(goal)}`;
  return `<label>Progresso manual (%)<input name="progress" type="range" min="0" max="100" value="${goal?.progress||0}"><output>${goal?.progress||0}%</output></label>`;
}
function qolTarget(goal){return `<label>Meta numérica<input name="target" type="number" min="1" value="${goal?.target||100}"></label>`}

goalDrawer=function(goalId,eraId='',questName='') {
  const identity=`${goalId||'new'}|${eraId}|${questName}`;if(ui.goalDrawerIdentity!==identity){ui.goalDrawerIdentity=identity;ui.goalDraftMode='';ui.goalDraftType=''}
  const goal=goalId?goalById(goalId):null, linkedQuest=goal?.questName||questName, quest=questByName(linkedQuest), mode=ui.goalDraftMode||goal?.mode||(linkedQuest?'quest':'manual'), type=ui.goalDraftType||goal?.type||(linkedQuest?'quest':'manual'), status=goal?.status||(Number(quest?.state)===2?'done':Number(quest?.state)===1?'active':'planned');
  if(['diaryTask','diaryTier','combatAchievement','collectionItem','collectionSource'].includes(mode)&&!progressionCatalogs.diaries.length&&!progressionLoading)setTimeout(()=>loadProgressionCatalogs(false),0);
  const types=[['manual','Meta livre'],['quest','Quest'],['skill','Skill'],['boss','Boss'],['raid','Raid'],['unlock','Desbloqueio'],['diary','Diary'],['combatAchievement','Combat Achievement'],['collectionLog','Collection Log'],['composite','Meta composta'],['gear','Gear'],['slayer','Slayer']];
  const slayerModes=`<option value="slayerTask" ${mode==='slayerTask'?'selected':''}>Task atual de Slayer</option><option value="slayerKills" ${mode==='slayerKills'?'selected':''}>Kills registradas no Bestiário</option>`;
  return `${drawerHead(goal?'EDITAR META':'NOVA META',goal?.title||linkedQuest||'Criar objetivo')}<form class="form drawer-form expanded-goal-form" data-goal-form><input type="hidden" name="id" value="${goal?.id||''}"><label>Nome<input name="title" required value="${esc(goal?.title||linkedQuest||'')}" placeholder="Ex: Slayer 85"></label><label>Descrição<textarea name="description" placeholder="Por que essa meta importa?">${esc(goal?.description||(linkedQuest?`Concluir ${linkedQuest} e avançar na jornada.`:''))}</textarea></label><div class="form-two"><label>Tipo<select name="type" data-goal-type>${types.map(([value,label])=>`<option value="${value}" ${type===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Status<select name="status">${['planned','active','paused','done'].map(value=>`<option value="${value}" ${status===value?'selected':''}>${statusLabel(value)}</option>`).join('')}</select></label></div><label>Capítulo do Roadmap<select name="eraId"><option value="">Sem capítulo</option>${[...state.eras].sort((a,b)=>a.order-b.order).map(era=>`<option value="${era.id}" ${(goal?.eraId||eraId)===era.id?'selected':''}>${esc(era.title)}</option>`).join('')}</select></label><label>Como calcular<select name="mode" data-goal-mode>${expandedModeOptions(mode)}${slayerModes}</select></label><div class="conditional-fields">${qolModeFields(goal,mode,linkedQuest)}</div><button class="primary-btn drawer-submit">${goal?'Salvar alterações':'Criar meta'}</button></form>`;
};

function qolLimitMarkup(html, selector, limit, kind) {
  const template=document.createElement('template');template.innerHTML=html;const container=template.content.querySelector(selector);if(!container)return html;const filters=template.content.querySelector('.achievement-filters');if(filters)filters.insertAdjacentHTML('beforeend',`<button class="ghost-btn filter-clear" data-clear-achievement-filters="${kind}">Limpar filtros</button>`);const children=[...container.children],total=children.length;children.slice(limit).forEach(node=>node.remove());if(total>limit)container.insertAdjacentHTML('afterend',`<div class="achievement-load-more"><button class="ghost-btn" data-achievement-more="${kind}">Mostrar mais (${Math.min(50,total-limit)} de ${total-limit} restantes)</button></div>`);return template.innerHTML;
}
const qolBaseDiariesPanel=diariesPanel,qolBaseCombatPanel=combatPanel,qolBaseCollectionPanel=collectionPanel;
diariesPanel=function(){return qolLimitMarkup(qolBaseDiariesPanel(),'.achievement-groups',ui.achievementLimits.diaries,'diaries')};
combatPanel=function(){return qolLimitMarkup(qolBaseCombatPanel(),'.ca-grid',ui.achievementLimits.combat,'combat')};
collectionPanel=function(){return qolLimitMarkup(qolBaseCollectionPanel(),'.collection-grid',ui.achievementLimits.collection,'collection')};

const qolBaseSettingsPage=settingsPage;
function qolHealth(label,ok,when,error=''){return `<article class="sync-health-item ${error?'error':ok?'ok':''}"><span><i></i>${label}</span><small>${error?esc(error):ok?`Atualizado ${formatDate(when)}`:'Ainda sem dados'}</small></article>`}
settingsPage=function(){
  const bank=typeof currentBank==='function'?currentBank():null,cl=state.progression.collectionLog,ca=state.progression.combatAchievements,diaries=state.progression.diaries;
  const catalogUpdated=progressionCatalogs.updatedAt||state.bosses.imagesUpdatedAt;
  return `${sectionHead('SAÚDE DAS INTEGRAÇÕES','Central de sincronização',`<button class="primary-btn" data-qol-sync-all>↻ Verificar tudo</button>`)}<section class="card"><div class="sync-health-grid">${qolHealth('Wise Old Man',!!state.lastSync,state.lastSync,state.integrationHealth?.womError)}${qolHealth('Ganhos semanais',!!state.gains.lastSync,state.gains.lastSync,state.integrationHealth?.gainsError)}${qolHealth('Quests',!!state.quests.lastSync,state.quests.lastSync,state.quests.syncError)}${qolHealth('Diaries',!!diaries.lastSync,diaries.lastSync)}${qolHealth('Combat Achievements',!!ca.lastSync,ca.lastSync)}${qolHealth('Collection Log',!!cl.lastSync,cl.lastSync)}${qolHealth('Catálogos da Wiki',!!catalogUpdated,catalogUpdated,progressionError||state.integrationHealth?.bossCatalogError)}${qolHealth('Banco',!!bank?.importedAt,bank?.importedAt)}${qolHealth('Mercado GE',!!marketData.updatedAt,marketData.updatedAt,marketData.error)}</div><div class="integration-actions"><button class="ghost-btn" data-sync>Wise Old Man</button><button class="ghost-btn" data-quest-sync>Quests e conquistas</button><button class="ghost-btn" data-load-progression>Catálogos</button></div></section>${qolBaseSettingsPage()}`;
};

const qolBaseSyncGains=syncGains;
syncGains=async function(){state.integrationHealth=state.integrationHealth||{};const before=state.gains.lastSync;await qolBaseSyncGains();state.integrationHealth.gainsError=state.gains.lastSync===before?'Dados semanais indisponíveis ou sem atualização':'';};
const qolBaseSyncAccount=syncAccount;
syncAccount=async function(){state.integrationHealth=state.integrationHealth||{};const before=state.lastSync;await qolBaseSyncAccount();state.integrationHealth.womError=state.lastSync===before?'A conta não respondeu nesta tentativa':'';try{persistProfiles()}catch{}};

const qolBaseWikiCatalog=loadWikiCatalog;
loadWikiCatalog=async function(){state.integrationHealth=state.integrationHealth||{};const before=state.bosses.catalog.length;await qolBaseWikiCatalog();state.integrationHealth.bossCatalogError=state.bosses.wikiLoaded?'':state.bosses.catalog.length===before?'Catálogo de bosses indisponível nesta tentativa':'';try{persistProfiles()}catch{}};

const qolBaseHistoryPage=historyPage;
historyPage=function(){return qolBaseHistoryPage().replace('<div class="filterbar">','<div class="filterbar"><button class="ghost-btn filter-clear" data-clear-history-filter>Limpar filtro</button>')};

const qolBaseToast=toast;
toast=function(message,action=''){qolBaseToast(message,action);if(action){clearTimeout(toast.timer);toast.timer=setTimeout(()=>document.querySelector('#toast')?.classList.remove('show'),8000)}};

const qolBaseSessionPage=sessionPage;
sessionPage=function(){return qolBaseSessionPage().replace('<div class="session-grid">',`<div class="session-smart-actions"><button class="ghost-btn" data-session-from-focus>✦ Gerar ações do foco</button><span class="muted">Tarefas não concluídas permanecem para a próxima visita.</span></div><div class="session-grid">`)};

let qolCalculatorResultKind='';
document.addEventListener('submit',event=>{const form=event.target;if(form.matches('[data-calc-skill],[data-calc-banked],[data-calc-combat],[data-calc-ge],[data-calc-drop],[data-calc-prayer],[data-calc-supplies]'))qolCalculatorResultKind=[...form.attributes].find(attribute=>attribute.name.startsWith('data-calc-'))?.name.replace('data-calc-','')||''},true);
const qolBaseEconomyMarket=economyMarket;
economyMarket=function(){return `<details open class="card economy-margin-tool"><summary>¤ Calculadora de margem do GE</summary><div class="calculator-layout"><div>${geCalculator()}</div>${calculatorResult&&qolCalculatorResultKind==='ge'?calculatorResultCard():''}</div></details>${qolBaseEconomyMarket()}`};
const qolBaseCalculatorsPage=calculatorsPage;
calculatorsPage=function(){if(ui.calculatorTab==='ge')ui.calculatorTab='skill';return qolBaseCalculatorsPage().replace('<button data-calculator-tab="ge"','<button hidden data-calculator-tab="ge"').replace('dados do personagem atual','GE foi integrada à Economia · dados do personagem atual')};

const qolBaseBankedCalculator=bankedCalculator;
bankedCalculator=function(){const bank=typeof currentBank==='function'?currentBank():null,items=(bank?.items||[]).slice().sort((a,b)=>String(a.name).localeCompare(String(b.name)));if(!items.length)return qolBaseBankedCalculator();return `<form class="calculator-card" data-calc-banked><div class="calc-title"><span>▣</span><div><small>BANKED XP · BANCO IMPORTADO</small><h3>Quanto XP existe no banco?</h3></div></div><label>Item do banco<select data-banked-item><option value="">Escolha um item para preencher a quantidade</option>${items.map(item=>`<option value="${Number(item.quantity)||0}">${esc(item.name)} · ${Number(item.quantity).toLocaleString('pt-BR')}</option>`).join('')}</select></label><div class="form-two"><label>Skill<select name="skill">${state.skills.map(item=>`<option>${item.name}</option>`).join('')}</select></label><label>Meta de nível<input name="target" type="number" min="2" max="126" value="99"></label></div><div class="form-two"><label>Quantidade de itens<input name="quantity" type="number" min="0" value="0"></label><label>XP por item<input name="xpItem" type="number" min=".01" step=".01" value="100"></label></div><button class="primary-btn">Calcular XP no banco</button></form>`};

prayerCalculator=function(){const prayers=[['Piety',40],['Rigour',40],['Augury',40],['Protect from Melee',20],['Protect from Missiles',20],['Protect from Magic',20],['Preserve',3],['Rapid Heal',6],['Redemption',20]];return `<form class="calculator-card" data-calc-prayer><div class="calc-title"><span>✧</span><div><small>PRAYER DRAIN</small><h3>Duração com prayer real</h3></div></div><label>Prayer ativa<select name="drain">${prayers.map(([name,drain])=>`<option value="${drain}">${name} · ${drain} pontos/min</option>`).join('')}</select></label><div class="form-two"><label>Prayer atual<input name="points" type="number" min="1" value="${skill('Prayer')?.current||70}"></label><label>Bônus de Prayer<input name="bonus" type="number" min="0" value="${aggregateGear(state.gearLab.current).prayer_bonus||0}"></label></div><button class="primary-btn">Calcular duração</button></form>`};

const qolBaseCheckpoints=checkpointsPlanner;
checkpointsPlanner=function(){const diaries=state.progression.diaries,ca=state.progression.combatAchievements,diaryGroups=progressionCatalogs.diaries||[],diaryTotal=diaryGroups.reduce((sum,group)=>sum+(group.tasks?.length||0),0),diaryDone=diaryGroups.reduce((sum,group)=>sum+(group.tasks||[]).filter(task=>diaryTaskDone(group.region,group.tier,task.index)).length,0),caCatalog=progressionCatalogs.combatAchievements||[],caDone=new Set((ca.completed||[]).map(Number)),caCompleted=caCatalog.filter(item=>caDone.has(Number(item.id))).length;return `${sectionHead('PROGRESSO SINCRONIZADO','Diaries e Combat Achievements',`<button class="primary-btn" data-route="achievements">Abrir Conquistas →</button>`)}<div class="merged-tool-note"><strong>Uma única fonte de verdade</strong><p>O Planejador agora usa o progresso sincronizado em Conquistas. Metas vinculadas continuam aparecendo normalmente no Roadmap.</p></div><div class="summary-grid">${progressSummaryCard('▤','Diaries',diaryTotal?`${diaryDone}/${diaryTotal} tarefas`:(diaries.lastSync?'Sincronizadas':'Pendentes'),diaries.lastSync?formatDate(diaries.lastSync):'Abra Conquistas para sincronizar',diaryTotal?safePercent(diaryDone,diaryTotal):0)}${progressSummaryCard('⚔','Combat Achievements',caCatalog.length?`${caCompleted}/${caCatalog.length} concluídos`:`${caDone.size} concluídos`,ca.lastSync?formatDate(ca.lastSync):'Aguardando WikiSync',caCatalog.length?safePercent(caCompleted,caCatalog.length):0)}</div>${state.planner.checkpoints.length?`<details class="card legacy-checkpoints"><summary>Checkpoints manuais antigos (${state.planner.checkpoints.length})</summary>${qolBaseCheckpoints()}</details>`:''}`};

const qolBasePvmPage=pvmPage;
pvmPage=function(){if(ui.pvmTab!=='combat')return qolBasePvmPage();const catalog=progressionCatalogs.combatAchievements,done=combatCompletedSet(),tabs=`<div class="rune-tabs pvm-tabs"><button data-pvm-tab="passport">⚔ Passaporte</button><button data-pvm-tab="combat" class="active">★ Combat Achievements</button><button data-pvm-tab="gear">♟ Gear Lab</button></div>`;const tiers=caTierOrder.map(tier=>{const rows=catalog.filter(item=>item.tier===tier);return {tier,done:rows.filter(item=>done.has(item.id)).length,total:rows.length}});return `${sectionHead('PASSAPORTE PVM','Resumo dos Combat Achievements',`<button class="primary-btn" data-route="achievements">Gerenciar em Conquistas →</button>`)}${tabs}<div class="merged-tool-note"><strong>Resumo contextual</strong><p>O catálogo completo e a criação de metas ficam em Conquistas; aqui você vê rapidamente sua prontidão para PvM.</p></div><div class="pvm-ca-summary">${tiers.map(row=>`<article><small>${row.tier}</small><strong>${row.done}/${row.total||'—'}</strong>${progressBar(row.total?safePercent(row.done,row.total):0)}</article>`).join('')}</div>`};

const qolBaseRender=render;
let qolDrawerWasOpen=false;
function qolApplyControlLabels(){const labels={'[data-goal-filter]':'Filtrar metas por status','[data-quest-filter]':'Filtrar quests','[data-slayer-filter]':'Filtrar bestiário de Slayer','[data-diary-region]':'Filtrar Diaries por região','[data-diary-tier]':'Filtrar Diaries por dificuldade','[data-ca-tier]':'Filtrar Combat Achievements por dificuldade','[data-ca-monster]':'Filtrar Combat Achievements por monstro','[data-ca-type]':'Filtrar Combat Achievements por tipo','[data-collection-source]':'Filtrar página do Collection Log','[data-history-filter]':'Filtrar histórico','[data-progression-search]':'Buscar conquistas','[data-market-search]':'Pesquisar item do Grand Exchange','[data-bank-search]':'Buscar item no banco'};Object.entries(labels).forEach(([selector,label])=>document.querySelectorAll(selector).forEach(control=>{if(!control.getAttribute('aria-label'))control.setAttribute('aria-label',label)}));const taskForm=document.querySelector('[data-task-form]');if(taskForm){taskForm.elements.text?.setAttribute('aria-label','Nova ação da sessão');taskForm.elements.goalId?.setAttribute('aria-label','Meta vinculada à nova ação')}document.querySelector('#fileBridge')?.setAttribute('aria-label','Selecionar arquivo')}
render=function(){qolBaseRender();qolApplyControlLabels();const open=!!ui.drawer;document.body.classList.toggle('drawer-open',open);const shell=document.querySelector('.app-shell');if(shell){if(open)shell.setAttribute('inert','');else shell.removeAttribute('inert')}if(open&&!qolDrawerWasOpen){const first=document.querySelector('.drawer input:not([type="hidden"]),.drawer select,.drawer textarea,.drawer button');setTimeout(()=>first?.focus({preventScroll:true}),0)}qolDrawerWasOpen=open;if(route==='character'&&ui.pendingSkill){const wanted=ui.pendingSkill;ui.pendingSkill='';setTimeout(()=>{const row=[...document.querySelectorAll('[data-skill-target]')].find(input=>input.dataset.skillTarget===wanted)?.closest('.skill-row,article,div');row?.scrollIntoView({behavior:'smooth',block:'center'});row?.classList.add('skill-flash')},40)}};

document.addEventListener('input',event=>{const input=event.target;if(input.matches('[data-catalog-search]')){const results=input.closest('.catalog-picker').querySelector('[data-catalog-results]');results.innerHTML=qolPickerRows(input.dataset.catalogSearch,input.value);const hidden=input.closest('.catalog-picker').querySelector(`input[name="${input.dataset.catalogSearch}"]`);hidden.value='';input.closest('.catalog-picker').querySelector('.catalog-selected').textContent='Escolha um resultado abaixo.'}if(input.matches('[name="progress"]'))input.closest('label')?.querySelector('output')?.replaceChildren(`${input.value}%`)});
document.addEventListener('change',event=>{const input=event.target;if(input.matches('[data-goal-mode]')){event.stopImmediatePropagation();ui.goalDraftMode=input.value;render();return}if(input.matches('[data-goal-type]')){event.stopImmediatePropagation();ui.goalDraftType=input.value;const defaults={quest:'quest',skill:'skill',boss:'boss',raid:'raid',diary:'diaryTask',combatAchievement:'combatAchievement',collectionLog:'collectionItem',composite:'composite',gear:'gearLoadout',slayer:'slayerKills',manual:'manual',unlock:'manual'};ui.goalDraftMode=defaults[input.value]||'manual';render();const mode=document.querySelector('[data-goal-mode]');if(mode)mode.value=ui.goalDraftMode;return}if(input.matches('[data-banked-item]')){const quantity=input.form?.elements.quantity;if(quantity)quantity.value=input.value}},true);
document.addEventListener('keydown',event=>{if(event.key!=='Tab'||!ui.drawer)return;const drawer=document.querySelector('.drawer'),focusable=[...drawer.querySelectorAll('button:not([disabled]),input:not([disabled]):not([type="hidden"]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(node=>node.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
document.addEventListener('click',async event=>{const option=event.target.closest('[data-catalog-option]');if(option){event.preventDefault();event.stopImmediatePropagation();const picker=option.closest('.catalog-picker');picker.querySelector(`input[name="${option.dataset.catalogOption}"]`).value=option.dataset.value;picker.querySelector('[data-catalog-search]').value=option.dataset.label;picker.querySelector('.catalog-selected').textContent=`Selecionado: ${option.dataset.label}`;return}const button=event.target.closest('button');if(!button)return;const undoable=['eraDelete','methodDelete','sessionDelete','upgradeDelete','routineDelete','dropDelete','checkpointDelete','deleteGearPreset'].some(key=>button.dataset[key]!==undefined);if(undoable){const before=JSON.stringify(state);snapshotForUndo();setTimeout(()=>{if(JSON.stringify(state)!==before)toast('Item removido','Desfazer')},0)}if(button.dataset.achievementMore){event.preventDefault();event.stopImmediatePropagation();ui.achievementLimits[button.dataset.achievementMore]+=50;render();return}if(button.dataset.clearAchievementFilters){event.preventDefault();event.stopImmediatePropagation();ui.progressionSearch='';ui.diaryRegion='all';ui.diaryTier='all';ui.caTier='all';ui.caMonster='all';ui.caType='all';ui.collectionSource='all';ui.progressionIncomplete=true;ui.achievementLimits[button.dataset.clearAchievementFilters]=button.dataset.clearAchievementFilters==='diaries'?8:button.dataset.clearAchievementFilters==='combat'?48:60;render();return}if(button.matches('[data-clear-history-filter]')){event.preventDefault();event.stopImmediatePropagation();ui.historyFilter='all';render();return}if(button.dataset.historyDelete){event.preventDefault();event.stopImmediatePropagation();snapshotForUndo();state.history=state.history.filter(item=>item.id!==button.dataset.historyDelete);save('Registro removido','Desfazer');render();return}if(button.dataset.characterSkill){event.preventDefault();event.stopImmediatePropagation();ui.pendingSkill=button.dataset.characterSkill;navigate('character');return}if(button.matches('[data-session-from-focus]')){event.preventDefault();event.stopImmediatePropagation();let added=0;state.dashboard.focus.map(goalById).filter(Boolean).forEach(goal=>{if(!state.tasks.some(task=>!task.done&&task.goalId===goal.id)){state.tasks.push({id:id('task'),text:`Avançar: ${goal.title}`,done:false,goalId:goal.id});added++}});save(added?`${added} ação(ões) criada(s) a partir do foco`:'As metas do foco já estão na sessão');render();return}if(button.matches('[data-qol-sync-all]')){event.preventDefault();event.stopImmediatePropagation();await syncAccount();await syncQuests(false);await loadProgressionCatalogs(false);if(!marketData.loaded)await loadMarketData(false);render();return}},true);

qolApplyControlLabels();
